services:
  frontend:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - arangodb
      - redis
  backend:
    build: .
    command:
      [
        'uvicorn',
        'app.main:app',
        '--host',
        '0.0.0.0',
        '--port',
        '8080',
        '--workers',
        '1',
      ]
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
      - ./logs:/vman3/logs
      - .settings.json:/vman3/settings.json
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
  arangodb:
    image: arangodb/arangodb:3.12.2
    env_file:
      - .env
    volumes:
      - vman3db:/var/lib/arangodb3
    ports:
      - '8529:8529'
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529
      # - --rocksdb.block-cache-size=1024MB
  redis:
    image: redis:7
    ports:
      - '6379:6379'
volumes:
  vman3db: