services:
  fro:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - arango-db

  arango-db:
    image: arangodb/arangodb:12
    env_file:
      - .env
    volumes:
      - vman3db:/var/lib/arangodb3
    ports:
      - '8529:8529'
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529

volumes:
  vman3db:
