services:
  fro:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - arango-db

  arango-db:
<<<<<<< HEAD
<<<<<<< HEAD
    image: arangodb/arangodb:3.12.2
=======
    image: arangodb/arangodb:12
>>>>>>> 90641a8 (clean docker)
=======
    image: arangodb/arangodb:3.12.2
>>>>>>> a22e059 (Fix query issues in shared va records fetching functions)
    env_file:
      - .env
    volumes:
      - vman3db:/var/lib/arangodb3
    ports:
      - '8529:8529'
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529

volumes:
  vman3db:
