version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
      # - frontend
      # - backend
      # - docs
    networks:
      - vman3-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  frontend:
    image: ilyatuu/vman3_frontend
    ports:
      - "4200:80"
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
    networks:
      - vman3-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  backend:
    image: ilyatuu/vman3_backend:latest
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--workers",
        "2"
      ]
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ccva_files:/app/ccva_files
      - app_data:/app
      - settings_json:/vman3/settings.json
      - uploads:/vman3/app/uploads
    networks:
      - vman3-net
    deploy:
      replicas: 3
      restart_policy:
        condition: any

  # docs:
  #   image: crisskimaryo/vman3_docs
  #   networks:
  #     - vman3-net
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: any

  arango-db:
    image: arangodb/arangodb:3.12.2
    env_file:
      - .env
    volumes:
      - vman3db:/var/lib/arangodb3
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529
      - --rocksdb.write-buffer-size=128MB
      - --rocksdb.total-write-buffer-size=512MB
    networks:
      - vman3-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  redis:
    image: redis:7
    command: redis-server --requirepass vman@1029
    ports:
      - "6370:6379"
    networks:
      - vman3-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  vman3-net:
    driver: overlay
    attachable: true


volumes:
  vman3db:
  ccva_files:
  app_data:
  uploads:
  settings_json:
