version: '3.8'

services:
  frontend:
    image: ilyatuu/vman3_frontend
    ports:
      - 4200:80
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
    depends_on:
      - backend
      - arango-db
    networks:
      - default

  backend:
    image: ilyatuu/vman3_backend
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
      - .settings.json:/vman3/settings.json
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env

    depends_on:
      - arangodb
      - redis

  arango-db:
    image: arangodb/arangodb:12
    env_file:
      - .env
    volumes:
      - vman3db:/var/lib/arangodb3
    ports:
      - '8529:8529'
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529

volumes:
  vman3db:
