version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vman3-net
    restart: always

  frontend:
    image: ilyatuu/vman3_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json
    networks:
      - vman3-net
    restart: always

  backend:
    image: ilyatuu/vman3_backend:latest
    command:
      [
        "gunicorn",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "-w",
        "3",
        "-b",
        "0.0.0.0:8080",
        "--timeout",
        "120",
        "app.main:app"
      ]
    ports:
      - "8080:8080"
    volumes:
      - ccva_files:/app/ccva_files
      - app_data:/app
      - settings_json:/vman3/settings.json
      - uploads:/vman3/app/uploads
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
    networks:
      - vman3-net
    restart: always

  arango-db:
    image: arangodb/arangodb:3.12.2
    ports:
      - "8529:8529"
    env_file:
      - .env
    volumes:
      - vman3db:/var/lib/arangodb3
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529
      - --rocksdb.write-buffer-size=128MB
      - --rocksdb.total-write-buffer-size=512MB
    networks:
      - vman3-net
    restart: always

  redis:
    image: redis:latest
    command: redis-server --requirepass vman@1029
    ports:
      - "6370:6379"
    networks:
      - vman3-net
    restart: always

networks:
  vman3-net:
    driver: bridge

volumes:
  vman3db:
  ccva_files:
  app_data:
  uploads:
  settings_json:
